# Generated by Django 5.2.1 on 2025-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short excerpt or summary of the post. If left blank, the first 50 words will be used.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Optional featured image for the blog post', null=True, upload_to='blog/featured_images/%Y/%m/'),
        ),
    ]
